// The master country & nationality list — the same for every enterprise and property,
// with nothing to configure (owner, 2026-09-25). International standards throughout:
//   - codes:  ISO 3166-1 — alpha-2 is what every "country" / "nationality" field stores;
//             alpha-3 is what passports carry (ICAO Doc 9303 MRZ), used by eRegistration OCR;
//   - names:  Unicode CLDR English short names (what browsers and phones show), generated
//             from ICU (Intl.DisplayNames) rather than typed by hand;
//   - flags:  the country-flag-icons SVG set, keyed by the same alpha-2 code.
// The nationality column (demonym, e.g. "Maldivian") has no ISO standard; it follows common
// English usage. XK (Kosovo) is a user-assigned code, included because passports use it.
// An enterprise can rename an entry or add its own on top of this list — see
// src/lib/nationalities.ts. Regenerating the table: see the note at the bottom.
export type CountryRecord = { alpha2: string; alpha3: string; name: string; nationality: string };

export const COUNTRIES: CountryRecord[] = [
  { alpha2: "AD", alpha3: "AND", name: "Andorra", nationality: "Andorran" },
  { alpha2: "AE", alpha3: "ARE", name: "United Arab Emirates", nationality: "Emirati" },
  { alpha2: "AF", alpha3: "AFG", name: "Afghanistan", nationality: "Afghan" },
  { alpha2: "AG", alpha3: "ATG", name: "Antigua & Barbuda", nationality: "Antiguan" },
  { alpha2: "AI", alpha3: "AIA", name: "Anguilla", nationality: "Anguillan" },
  { alpha2: "AL", alpha3: "ALB", name: "Albania", nationality: "Albanian" },
  { alpha2: "AM", alpha3: "ARM", name: "Armenia", nationality: "Armenian" },
  { alpha2: "AO", alpha3: "AGO", name: "Angola", nationality: "Angolan" },
  { alpha2: "AQ", alpha3: "ATA", name: "Antarctica", nationality: "Antarctic" },
  { alpha2: "AR", alpha3: "ARG", name: "Argentina", nationality: "Argentine" },
  { alpha2: "AS", alpha3: "ASM", name: "American Samoa", nationality: "American Samoan" },
  { alpha2: "AT", alpha3: "AUT", name: "Austria", nationality: "Austrian" },
  { alpha2: "AU", alpha3: "AUS", name: "Australia", nationality: "Australian" },
  { alpha2: "AW", alpha3: "ABW", name: "Aruba", nationality: "Aruban" },
  { alpha2: "AX", alpha3: "ALA", name: "Åland Islands", nationality: "Ålander" },
  { alpha2: "AZ", alpha3: "AZE", name: "Azerbaijan", nationality: "Azerbaijani" },
  { alpha2: "BA", alpha3: "BIH", name: "Bosnia & Herzegovina", nationality: "Bosnian" },
  { alpha2: "BB", alpha3: "BRB", name: "Barbados", nationality: "Barbadian" },
  { alpha2: "BD", alpha3: "BGD", name: "Bangladesh", nationality: "Bangladeshi" },
  { alpha2: "BE", alpha3: "BEL", name: "Belgium", nationality: "Belgian" },
  { alpha2: "BF", alpha3: "BFA", name: "Burkina Faso", nationality: "Burkinabé" },
  { alpha2: "BG", alpha3: "BGR", name: "Bulgaria", nationality: "Bulgarian" },
  { alpha2: "BH", alpha3: "BHR", name: "Bahrain", nationality: "Bahraini" },
  { alpha2: "BI", alpha3: "BDI", name: "Burundi", nationality: "Burundian" },
  { alpha2: "BJ", alpha3: "BEN", name: "Benin", nationality: "Beninese" },
  { alpha2: "BL", alpha3: "BLM", name: "St. Barthélemy", nationality: "Barthélemois" },
  { alpha2: "BM", alpha3: "BMU", name: "Bermuda", nationality: "Bermudian" },
  { alpha2: "BN", alpha3: "BRN", name: "Brunei", nationality: "Bruneian" },
  { alpha2: "BO", alpha3: "BOL", name: "Bolivia", nationality: "Bolivian" },
  { alpha2: "BQ", alpha3: "BES", name: "Caribbean Netherlands", nationality: "Bonairean" },
  { alpha2: "BR", alpha3: "BRA", name: "Brazil", nationality: "Brazilian" },
  { alpha2: "BS", alpha3: "BHS", name: "Bahamas", nationality: "Bahamian" },
  { alpha2: "BT", alpha3: "BTN", name: "Bhutan", nationality: "Bhutanese" },
  { alpha2: "BV", alpha3: "BVT", name: "Bouvet Island", nationality: "Bouvet Islander" },
  { alpha2: "BW", alpha3: "BWA", name: "Botswana", nationality: "Motswana" },
  { alpha2: "BY", alpha3: "BLR", name: "Belarus", nationality: "Belarusian" },
  { alpha2: "BZ", alpha3: "BLZ", name: "Belize", nationality: "Belizean" },
  { alpha2: "CA", alpha3: "CAN", name: "Canada", nationality: "Canadian" },
  { alpha2: "CC", alpha3: "CCK", name: "Cocos (Keeling) Islands", nationality: "Cocos Islander" },
  { alpha2: "CD", alpha3: "COD", name: "Congo - Kinshasa", nationality: "Congolese (DRC)" },
  { alpha2: "CF", alpha3: "CAF", name: "Central African Republic", nationality: "Central African" },
  { alpha2: "CG", alpha3: "COG", name: "Congo - Brazzaville", nationality: "Congolese" },
  { alpha2: "CH", alpha3: "CHE", name: "Switzerland", nationality: "Swiss" },
  { alpha2: "CI", alpha3: "CIV", name: "Côte d’Ivoire", nationality: "Ivorian" },
  { alpha2: "CK", alpha3: "COK", name: "Cook Islands", nationality: "Cook Islander" },
  { alpha2: "CL", alpha3: "CHL", name: "Chile", nationality: "Chilean" },
  { alpha2: "CM", alpha3: "CMR", name: "Cameroon", nationality: "Cameroonian" },
  { alpha2: "CN", alpha3: "CHN", name: "China", nationality: "Chinese" },
  { alpha2: "CO", alpha3: "COL", name: "Colombia", nationality: "Colombian" },
  { alpha2: "CR", alpha3: "CRI", name: "Costa Rica", nationality: "Costa Rican" },
  { alpha2: "CU", alpha3: "CUB", name: "Cuba", nationality: "Cuban" },
  { alpha2: "CV", alpha3: "CPV", name: "Cape Verde", nationality: "Cape Verdean" },
  { alpha2: "CW", alpha3: "CUW", name: "Curaçao", nationality: "Curaçaoan" },
  { alpha2: "CX", alpha3: "CXR", name: "Christmas Island", nationality: "Christmas Islander" },
  { alpha2: "CY", alpha3: "CYP", name: "Cyprus", nationality: "Cypriot" },
  { alpha2: "CZ", alpha3: "CZE", name: "Czechia", nationality: "Czech" },
  { alpha2: "DE", alpha3: "DEU", name: "Germany", nationality: "German" },
  { alpha2: "DJ", alpha3: "DJI", name: "Djibouti", nationality: "Djiboutian" },
  { alpha2: "DK", alpha3: "DNK", name: "Denmark", nationality: "Danish" },
  { alpha2: "DM", alpha3: "DMA", name: "Dominica", nationality: "Dominican (Dominica)" },
  { alpha2: "DO", alpha3: "DOM", name: "Dominican Republic", nationality: "Dominican" },
  { alpha2: "DZ", alpha3: "DZA", name: "Algeria", nationality: "Algerian" },
  { alpha2: "EC", alpha3: "ECU", name: "Ecuador", nationality: "Ecuadorian" },
  { alpha2: "EE", alpha3: "EST", name: "Estonia", nationality: "Estonian" },
  { alpha2: "EG", alpha3: "EGY", name: "Egypt", nationality: "Egyptian" },
  { alpha2: "EH", alpha3: "ESH", name: "Western Sahara", nationality: "Sahrawi" },
  { alpha2: "ER", alpha3: "ERI", name: "Eritrea", nationality: "Eritrean" },
  { alpha2: "ES", alpha3: "ESP", name: "Spain", nationality: "Spanish" },
  { alpha2: "ET", alpha3: "ETH", name: "Ethiopia", nationality: "Ethiopian" },
  { alpha2: "FI", alpha3: "FIN", name: "Finland", nationality: "Finnish" },
  { alpha2: "FJ", alpha3: "FJI", name: "Fiji", nationality: "Fijian" },
  { alpha2: "FK", alpha3: "FLK", name: "Falkland Islands", nationality: "Falkland Islander" },
  { alpha2: "FM", alpha3: "FSM", name: "Micronesia", nationality: "Micronesian" },
  { alpha2: "FO", alpha3: "FRO", name: "Faroe Islands", nationality: "Faroese" },
  { alpha2: "FR", alpha3: "FRA", name: "France", nationality: "French" },
  { alpha2: "GA", alpha3: "GAB", name: "Gabon", nationality: "Gabonese" },
  { alpha2: "GB", alpha3: "GBR", name: "United Kingdom", nationality: "British" },
  { alpha2: "GD", alpha3: "GRD", name: "Grenada", nationality: "Grenadian" },
  { alpha2: "GE", alpha3: "GEO", name: "Georgia", nationality: "Georgian" },
  { alpha2: "GF", alpha3: "GUF", name: "French Guiana", nationality: "French Guianese" },
  { alpha2: "GG", alpha3: "GGY", name: "Guernsey", nationality: "Guernsey" },
  { alpha2: "GH", alpha3: "GHA", name: "Ghana", nationality: "Ghanaian" },
  { alpha2: "GI", alpha3: "GIB", name: "Gibraltar", nationality: "Gibraltarian" },
  { alpha2: "GL", alpha3: "GRL", name: "Greenland", nationality: "Greenlandic" },
  { alpha2: "GM", alpha3: "GMB", name: "Gambia", nationality: "Gambian" },
  { alpha2: "GN", alpha3: "GIN", name: "Guinea", nationality: "Guinean" },
  { alpha2: "GP", alpha3: "GLP", name: "Guadeloupe", nationality: "Guadeloupean" },
  { alpha2: "GQ", alpha3: "GNQ", name: "Equatorial Guinea", nationality: "Equatorial Guinean" },
  { alpha2: "GR", alpha3: "GRC", name: "Greece", nationality: "Greek" },
  { alpha2: "GS", alpha3: "SGS", name: "South Georgia & South Sandwich Islands", nationality: "South Georgia Islander" },
  { alpha2: "GT", alpha3: "GTM", name: "Guatemala", nationality: "Guatemalan" },
  { alpha2: "GU", alpha3: "GUM", name: "Guam", nationality: "Guamanian" },
  { alpha2: "GW", alpha3: "GNB", name: "Guinea-Bissau", nationality: "Bissau-Guinean" },
  { alpha2: "GY", alpha3: "GUY", name: "Guyana", nationality: "Guyanese" },
  { alpha2: "HK", alpha3: "HKG", name: "Hong Kong SAR China", nationality: "Hong Konger" },
  { alpha2: "HM", alpha3: "HMD", name: "Heard & McDonald Islands", nationality: "Heard Island" },
  { alpha2: "HN", alpha3: "HND", name: "Honduras", nationality: "Honduran" },
  { alpha2: "HR", alpha3: "HRV", name: "Croatia", nationality: "Croatian" },
  { alpha2: "HT", alpha3: "HTI", name: "Haiti", nationality: "Haitian" },
  { alpha2: "HU", alpha3: "HUN", name: "Hungary", nationality: "Hungarian" },
  { alpha2: "ID", alpha3: "IDN", name: "Indonesia", nationality: "Indonesian" },
  { alpha2: "IE", alpha3: "IRL", name: "Ireland", nationality: "Irish" },
  { alpha2: "IL", alpha3: "ISR", name: "Israel", nationality: "Israeli" },
  { alpha2: "IM", alpha3: "IMN", name: "Isle of Man", nationality: "Manx" },
  { alpha2: "IN", alpha3: "IND", name: "India", nationality: "Indian" },
  { alpha2: "IO", alpha3: "IOT", name: "British Indian Ocean Territory", nationality: "British Indian Ocean Territory" },
  { alpha2: "IQ", alpha3: "IRQ", name: "Iraq", nationality: "Iraqi" },
  { alpha2: "IR", alpha3: "IRN", name: "Iran", nationality: "Iranian" },
  { alpha2: "IS", alpha3: "ISL", name: "Iceland", nationality: "Icelandic" },
  { alpha2: "IT", alpha3: "ITA", name: "Italy", nationality: "Italian" },
  { alpha2: "JE", alpha3: "JEY", name: "Jersey", nationality: "Jersey" },
  { alpha2: "JM", alpha3: "JAM", name: "Jamaica", nationality: "Jamaican" },
  { alpha2: "JO", alpha3: "JOR", name: "Jordan", nationality: "Jordanian" },
  { alpha2: "JP", alpha3: "JPN", name: "Japan", nationality: "Japanese" },
  { alpha2: "KE", alpha3: "KEN", name: "Kenya", nationality: "Kenyan" },
  { alpha2: "KG", alpha3: "KGZ", name: "Kyrgyzstan", nationality: "Kyrgyz" },
  { alpha2: "KH", alpha3: "KHM", name: "Cambodia", nationality: "Cambodian" },
  { alpha2: "KI", alpha3: "KIR", name: "Kiribati", nationality: "I-Kiribati" },
  { alpha2: "KM", alpha3: "COM", name: "Comoros", nationality: "Comoran" },
  { alpha2: "KN", alpha3: "KNA", name: "St. Kitts & Nevis", nationality: "Kittitian or Nevisian" },
  { alpha2: "KP", alpha3: "PRK", name: "North Korea", nationality: "North Korean" },
  { alpha2: "KR", alpha3: "KOR", name: "South Korea", nationality: "South Korean" },
  { alpha2: "KW", alpha3: "KWT", name: "Kuwait", nationality: "Kuwaiti" },
  { alpha2: "KY", alpha3: "CYM", name: "Cayman Islands", nationality: "Caymanian" },
  { alpha2: "KZ", alpha3: "KAZ", name: "Kazakhstan", nationality: "Kazakh" },
  { alpha2: "LA", alpha3: "LAO", name: "Laos", nationality: "Lao" },
  { alpha2: "LB", alpha3: "LBN", name: "Lebanon", nationality: "Lebanese" },
  { alpha2: "LC", alpha3: "LCA", name: "St. Lucia", nationality: "Saint Lucian" },
  { alpha2: "LI", alpha3: "LIE", name: "Liechtenstein", nationality: "Liechtensteiner" },
  { alpha2: "LK", alpha3: "LKA", name: "Sri Lanka", nationality: "Sri Lankan" },
  { alpha2: "LR", alpha3: "LBR", name: "Liberia", nationality: "Liberian" },
  { alpha2: "LS", alpha3: "LSO", name: "Lesotho", nationality: "Mosotho" },
  { alpha2: "LT", alpha3: "LTU", name: "Lithuania", nationality: "Lithuanian" },
  { alpha2: "LU", alpha3: "LUX", name: "Luxembourg", nationality: "Luxembourgish" },
  { alpha2: "LV", alpha3: "LVA", name: "Latvia", nationality: "Latvian" },
  { alpha2: "LY", alpha3: "LBY", name: "Libya", nationality: "Libyan" },
  { alpha2: "MA", alpha3: "MAR", name: "Morocco", nationality: "Moroccan" },
  { alpha2: "MC", alpha3: "MCO", name: "Monaco", nationality: "Monégasque" },
  { alpha2: "MD", alpha3: "MDA", name: "Moldova", nationality: "Moldovan" },
  { alpha2: "ME", alpha3: "MNE", name: "Montenegro", nationality: "Montenegrin" },
  { alpha2: "MF", alpha3: "MAF", name: "St. Martin", nationality: "Saint-Martinoise" },
  { alpha2: "MG", alpha3: "MDG", name: "Madagascar", nationality: "Malagasy" },
  { alpha2: "MH", alpha3: "MHL", name: "Marshall Islands", nationality: "Marshallese" },
  { alpha2: "MK", alpha3: "MKD", name: "North Macedonia", nationality: "Macedonian" },
  { alpha2: "ML", alpha3: "MLI", name: "Mali", nationality: "Malian" },
  { alpha2: "MM", alpha3: "MMR", name: "Myanmar (Burma)", nationality: "Burmese" },
  { alpha2: "MN", alpha3: "MNG", name: "Mongolia", nationality: "Mongolian" },
  { alpha2: "MO", alpha3: "MAC", name: "Macao SAR China", nationality: "Macanese" },
  { alpha2: "MP", alpha3: "MNP", name: "Northern Mariana Islands", nationality: "Northern Marianan" },
  { alpha2: "MQ", alpha3: "MTQ", name: "Martinique", nationality: "Martinican" },
  { alpha2: "MR", alpha3: "MRT", name: "Mauritania", nationality: "Mauritanian" },
  { alpha2: "MS", alpha3: "MSR", name: "Montserrat", nationality: "Montserratian" },
  { alpha2: "MT", alpha3: "MLT", name: "Malta", nationality: "Maltese" },
  { alpha2: "MU", alpha3: "MUS", name: "Mauritius", nationality: "Mauritian" },
  { alpha2: "MV", alpha3: "MDV", name: "Maldives", nationality: "Maldivian" },
  { alpha2: "MW", alpha3: "MWI", name: "Malawi", nationality: "Malawian" },
  { alpha2: "MX", alpha3: "MEX", name: "Mexico", nationality: "Mexican" },
  { alpha2: "MY", alpha3: "MYS", name: "Malaysia", nationality: "Malaysian" },
  { alpha2: "MZ", alpha3: "MOZ", name: "Mozambique", nationality: "Mozambican" },
  { alpha2: "NA", alpha3: "NAM", name: "Namibia", nationality: "Namibian" },
  { alpha2: "NC", alpha3: "NCL", name: "New Caledonia", nationality: "New Caledonian" },
  { alpha2: "NE", alpha3: "NER", name: "Niger", nationality: "Nigerien" },
  { alpha2: "NF", alpha3: "NFK", name: "Norfolk Island", nationality: "Norfolk Islander" },
  { alpha2: "NG", alpha3: "NGA", name: "Nigeria", nationality: "Nigerian" },
  { alpha2: "NI", alpha3: "NIC", name: "Nicaragua", nationality: "Nicaraguan" },
  { alpha2: "NL", alpha3: "NLD", name: "Netherlands", nationality: "Dutch" },
  { alpha2: "NO", alpha3: "NOR", name: "Norway", nationality: "Norwegian" },
  { alpha2: "NP", alpha3: "NPL", name: "Nepal", nationality: "Nepali" },
  { alpha2: "NR", alpha3: "NRU", name: "Nauru", nationality: "Nauruan" },
  { alpha2: "NU", alpha3: "NIU", name: "Niue", nationality: "Niuean" },
  { alpha2: "NZ", alpha3: "NZL", name: "New Zealand", nationality: "New Zealander" },
  { alpha2: "OM", alpha3: "OMN", name: "Oman", nationality: "Omani" },
  { alpha2: "PA", alpha3: "PAN", name: "Panama", nationality: "Panamanian" },
  { alpha2: "PE", alpha3: "PER", name: "Peru", nationality: "Peruvian" },
  { alpha2: "PF", alpha3: "PYF", name: "French Polynesia", nationality: "French Polynesian" },
  { alpha2: "PG", alpha3: "PNG", name: "Papua New Guinea", nationality: "Papua New Guinean" },
  { alpha2: "PH", alpha3: "PHL", name: "Philippines", nationality: "Filipino" },
  { alpha2: "PK", alpha3: "PAK", name: "Pakistan", nationality: "Pakistani" },
  { alpha2: "PL", alpha3: "POL", name: "Poland", nationality: "Polish" },
  { alpha2: "PM", alpha3: "SPM", name: "St. Pierre & Miquelon", nationality: "Saint-Pierrais" },
  { alpha2: "PN", alpha3: "PCN", name: "Pitcairn Islands", nationality: "Pitcairn Islander" },
  { alpha2: "PR", alpha3: "PRI", name: "Puerto Rico", nationality: "Puerto Rican" },
  { alpha2: "PS", alpha3: "PSE", name: "Palestinian Territories", nationality: "Palestinian" },
  { alpha2: "PT", alpha3: "PRT", name: "Portugal", nationality: "Portuguese" },
  { alpha2: "PW", alpha3: "PLW", name: "Palau", nationality: "Palauan" },
  { alpha2: "PY", alpha3: "PRY", name: "Paraguay", nationality: "Paraguayan" },
  { alpha2: "QA", alpha3: "QAT", name: "Qatar", nationality: "Qatari" },
  { alpha2: "RE", alpha3: "REU", name: "Réunion", nationality: "Réunionese" },
  { alpha2: "RO", alpha3: "ROU", name: "Romania", nationality: "Romanian" },
  { alpha2: "RS", alpha3: "SRB", name: "Serbia", nationality: "Serbian" },
  { alpha2: "RU", alpha3: "RUS", name: "Russia", nationality: "Russian" },
  { alpha2: "RW", alpha3: "RWA", name: "Rwanda", nationality: "Rwandan" },
  { alpha2: "SA", alpha3: "SAU", name: "Saudi Arabia", nationality: "Saudi" },
  { alpha2: "SB", alpha3: "SLB", name: "Solomon Islands", nationality: "Solomon Islander" },
  { alpha2: "SC", alpha3: "SYC", name: "Seychelles", nationality: "Seychellois" },
  { alpha2: "SD", alpha3: "SDN", name: "Sudan", nationality: "Sudanese" },
  { alpha2: "SE", alpha3: "SWE", name: "Sweden", nationality: "Swedish" },
  { alpha2: "SG", alpha3: "SGP", name: "Singapore", nationality: "Singaporean" },
  { alpha2: "SH", alpha3: "SHN", name: "St. Helena", nationality: "Saint Helenian" },
  { alpha2: "SI", alpha3: "SVN", name: "Slovenia", nationality: "Slovenian" },
  { alpha2: "SJ", alpha3: "SJM", name: "Svalbard & Jan Mayen", nationality: "Svalbard" },
  { alpha2: "SK", alpha3: "SVK", name: "Slovakia", nationality: "Slovak" },
  { alpha2: "SL", alpha3: "SLE", name: "Sierra Leone", nationality: "Sierra Leonean" },
  { alpha2: "SM", alpha3: "SMR", name: "San Marino", nationality: "Sammarinese" },
  { alpha2: "SN", alpha3: "SEN", name: "Senegal", nationality: "Senegalese" },
  { alpha2: "SO", alpha3: "SOM", name: "Somalia", nationality: "Somali" },
  { alpha2: "SR", alpha3: "SUR", name: "Suriname", nationality: "Surinamese" },
  { alpha2: "SS", alpha3: "SSD", name: "South Sudan", nationality: "South Sudanese" },
  { alpha2: "ST", alpha3: "STP", name: "São Tomé & Príncipe", nationality: "São Toméan" },
  { alpha2: "SV", alpha3: "SLV", name: "El Salvador", nationality: "Salvadoran" },
  { alpha2: "SX", alpha3: "SXM", name: "Sint Maarten", nationality: "Sint Maartener" },
  { alpha2: "SY", alpha3: "SYR", name: "Syria", nationality: "Syrian" },
  { alpha2: "SZ", alpha3: "SWZ", name: "Eswatini", nationality: "Swazi" },
  { alpha2: "TC", alpha3: "TCA", name: "Turks & Caicos Islands", nationality: "Turks and Caicos Islander" },
  { alpha2: "TD", alpha3: "TCD", name: "Chad", nationality: "Chadian" },
  { alpha2: "TF", alpha3: "ATF", name: "French Southern Territories", nationality: "French Southern Territories" },
  { alpha2: "TG", alpha3: "TGO", name: "Togo", nationality: "Togolese" },
  { alpha2: "TH", alpha3: "THA", name: "Thailand", nationality: "Thai" },
  { alpha2: "TJ", alpha3: "TJK", name: "Tajikistan", nationality: "Tajik" },
  { alpha2: "TK", alpha3: "TKL", name: "Tokelau", nationality: "Tokelauan" },
  { alpha2: "TL", alpha3: "TLS", name: "Timor-Leste", nationality: "Timorese" },
  { alpha2: "TM", alpha3: "TKM", name: "Turkmenistan", nationality: "Turkmen" },
  { alpha2: "TN", alpha3: "TUN", name: "Tunisia", nationality: "Tunisian" },
  { alpha2: "TO", alpha3: "TON", name: "Tonga", nationality: "Tongan" },
  { alpha2: "TR", alpha3: "TUR", name: "Türkiye", nationality: "Turkish" },
  { alpha2: "TT", alpha3: "TTO", name: "Trinidad & Tobago", nationality: "Trinidadian and Tobagonian" },
  { alpha2: "TV", alpha3: "TUV", name: "Tuvalu", nationality: "Tuvaluan" },
  { alpha2: "TW", alpha3: "TWN", name: "Taiwan", nationality: "Taiwanese" },
  { alpha2: "TZ", alpha3: "TZA", name: "Tanzania", nationality: "Tanzanian" },
  { alpha2: "UA", alpha3: "UKR", name: "Ukraine", nationality: "Ukrainian" },
  { alpha2: "UG", alpha3: "UGA", name: "Uganda", nationality: "Ugandan" },
  { alpha2: "UM", alpha3: "UMI", name: "U.S. Outlying Islands", nationality: "U.S. Minor Outlying Islands" },
  { alpha2: "US", alpha3: "USA", name: "United States", nationality: "American" },
  { alpha2: "UY", alpha3: "URY", name: "Uruguay", nationality: "Uruguayan" },
  { alpha2: "UZ", alpha3: "UZB", name: "Uzbekistan", nationality: "Uzbek" },
  { alpha2: "VA", alpha3: "VAT", name: "Vatican City", nationality: "Vatican" },
  { alpha2: "VC", alpha3: "VCT", name: "St. Vincent & Grenadines", nationality: "Vincentian" },
  { alpha2: "VE", alpha3: "VEN", name: "Venezuela", nationality: "Venezuelan" },
  { alpha2: "VG", alpha3: "VGB", name: "British Virgin Islands", nationality: "British Virgin Islander" },
  { alpha2: "VI", alpha3: "VIR", name: "U.S. Virgin Islands", nationality: "U.S. Virgin Islander" },
  { alpha2: "VN", alpha3: "VNM", name: "Vietnam", nationality: "Vietnamese" },
  { alpha2: "VU", alpha3: "VUT", name: "Vanuatu", nationality: "Ni-Vanuatu" },
  { alpha2: "WF", alpha3: "WLF", name: "Wallis & Futuna", nationality: "Wallisian or Futunan" },
  { alpha2: "WS", alpha3: "WSM", name: "Samoa", nationality: "Samoan" },
  { alpha2: "XK", alpha3: "XKX", name: "Kosovo", nationality: "Kosovar" },
  { alpha2: "YE", alpha3: "YEM", name: "Yemen", nationality: "Yemeni" },
  { alpha2: "YT", alpha3: "MYT", name: "Mayotte", nationality: "Mahoran" },
  { alpha2: "ZA", alpha3: "ZAF", name: "South Africa", nationality: "South African" },
  { alpha2: "ZM", alpha3: "ZMB", name: "Zambia", nationality: "Zambian" },
  { alpha2: "ZW", alpha3: "ZWE", name: "Zimbabwe", nationality: "Zimbabwean" },
];

const BY_ALPHA2 = new Map(COUNTRIES.map((c) => [c.alpha2, c]));
const BY_ALPHA3 = new Map(COUNTRIES.map((c) => [c.alpha3, c]));
const BY_NAME = new Map(COUNTRIES.map((c) => [c.name.toUpperCase(), c]));
const BY_NATIONALITY = new Map(COUNTRIES.map((c) => [c.nationality.toUpperCase(), c]));

// Accepts an alpha-2 code, an alpha-3 code, a country name or a nationality ("British") —
// this app has all of them depending on the path the value came in through (a picker,
// guest-typed eRegistration text, an OCR'd MRZ). Exact matches only; returns undefined
// rather than guessing when nothing matches.
export function findCountry(value: string | null | undefined): CountryRecord | undefined {
  if (!value) return undefined;
  const v = value.trim().toUpperCase();
  if (!v) return undefined;
  if (v.length === 2) return BY_ALPHA2.get(v);
  if (v.length === 3) return BY_ALPHA3.get(v) ?? BY_NAME.get(v) ?? BY_NATIONALITY.get(v);
  return BY_NAME.get(v) ?? BY_NATIONALITY.get(v);
}

// Best-effort display name: resolves a recognized code to its canonical name; anything
// else (a demonym like "British", or a name we don't have) is returned unchanged rather
// than blanked out.
export function countryNameFor(value: string | null | undefined): string | null {
  if (!value) return null;
  return findCountry(value)?.name ?? value;
}

// Alpha-2 code for flag lookup, or undefined if the value isn't a recognized country or
// nationality (exact match on the master list — never a guess).
export function alpha2For(value: string | null | undefined): string | undefined {
  return findCountry(value)?.alpha2;
}

/** The standard nationality for a code — "MV" → "Maldivian". */
export function nationalityFor(value: string | null | undefined): string | null {
  if (!value) return null;
  return findCountry(value)?.nationality ?? value;
}

// Regenerating COUNTRIES: the alpha-2/alpha-3 pairs are ISO 3166-1; each name is
// new Intl.DisplayNames(["en"], { type: "region" }).of(alpha2) (Unicode CLDR via ICU); the
// nationality is maintained here by hand. Keep the table sorted by alpha-2.
