import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { requireSession, requirePermission, assertPropertyModuleAccess, toErrorResponse } from "@/lib/scope";
import { expandScheduleDates } from "@/lib/excursions";
import { logActivity } from "@/lib/activity-log";

// Expands every active ExcursionSchedule for an ExcursionType into ExcursionDeparture
// rows, from today through `through` (inclusive). Idempotent by design: any date that
// already has a departure for that (excursionTypeId, date, time) — whether it was
// generated by an earlier run or hand-added/edited by staff — is skipped, never
// touched. This is the "hybrid" scheduling model's generation half; see
// .agents/docs/EXCURSIONS_PLAN.md.
export async function POST(request: Request) {
  try {
    const ctx = await requireSession();
    requirePermission(ctx, "CONTROLS", "create");

    const body = await request.json();
    if (!body.excursionTypeId || !body.through) {
      return NextResponse.json({ error: "excursionTypeId and through (date) are required" }, { status: 400 });
    }

    const through = new Date(body.through);
    if (isNaN(through.getTime())) {
      return NextResponse.json({ error: "through must be a valid date" }, { status: 400 });
    }

    const excursionType = await prisma.excursionType.findUnique({
      where: { id: body.excursionTypeId },
      include: { schedules: { where: { isActive: true } } },
    });
    if (!excursionType) {
      return NextResponse.json({ error: "Excursion type not found" }, { status: 404 });
    }
    await assertPropertyModuleAccess(ctx, excursionType.propertyId, "EXCURSIONS");

    if (excursionType.schedules.length === 0) {
      return NextResponse.json({ error: "This excursion type has no active recurring schedules to generate from" }, { status: 400 });
    }

    const today = new Date();
    let created = 0;
    let skipped = 0;

    for (const schedule of excursionType.schedules) {
      const dates = expandScheduleDates(schedule.daysOfWeek, today, through);
      for (const date of dates) {
        const existing = await prisma.excursionDeparture.findUnique({
          where: {
            excursionTypeId_departureDate_departureTime: {
              excursionTypeId: excursionType.id,
              departureDate: date,
              departureTime: schedule.departureTime,
            },
          },
        });
        if (existing) {
          skipped++;
          continue;
        }
        await prisma.excursionDeparture.create({
          data: {
            excursionTypeId: excursionType.id,
            scheduleId: schedule.id,
            departureDate: date,
            departureTime: schedule.departureTime,
            meetingTime: schedule.meetingTime,
            meetingPoint: schedule.meetingPoint,
            capacity: schedule.capacity,
            minCapacity: schedule.minCapacity,
          },
        });
        created++;
      }
    }

    await logActivity({
      ctx, module: "CONTROLS", action: "CREATE", entityType: "ExcursionDeparture",
      description: `Generated ${created} departure(s) for "${excursionType.name}" through ${through.toISOString().slice(0, 10)} (${skipped} already existed)`,
    });

    return NextResponse.json({ created, skipped });
  } catch (error) {
    const { status, body } = toErrorResponse(error);
    return NextResponse.json(body, { status });
  }
}
