import { prisma } from "@/lib/db"
import { STANDARD_CHARGE_CODES, CANONICAL_GROUPS, OUTLET_CODE_TEMPLATES, SYSTEM_SEED_CODES } from "@/lib/posting/charge-tree"

// One-off cleanup (owner, 2026-09-24): properties created before charge codes became the
// property's own still carry the DEMO chart the seeder used to add — 2001–2004, meal plans,
// spa, transport… — and the subgroup + codes every new outlet was given. New properties
// get only the system codes now (DECISIONS.md 2026-09-24); this brings the old ones in line.
//
// Conservative by design — a demo code is only touched when it is still EXACTLY what the
// seeder created (same number AND description; a renamed code is the property's own):
//   - posted to (folio lines or payments)     → deactivated, never deleted (history stays);
//   - still used by setup (rate plan, allocation, payment method, fee rule, spa
//     treatment, excursion type, transport, routing rule, or a generate from one of the
//     property's own codes)                   → kept, and reported;
//   - otherwise                               → deleted. Its outlet links go with it — the
//     outlet provisioning made them, not the property.
// A demo subgroup (the seeded defaults, or one outlet provisioning made) is deleted once
// no code is left in it. System codes and the canonical groups are never touched.

const SYSTEM_CODES = new Set(SYSTEM_SEED_CODES.map((c) => c.code))
const DEMO_CODES = new Map(STANDARD_CHARGE_CODES.filter((c) => !c.isSystem).map((c) => [c.code, c.description]))
// The seeded subgroups that hold no system code — the demo defaults.
const SYSTEM_SUBGROUPS = new Set(SYSTEM_SEED_CODES.map((c) => c.subgroupCode))
const DEMO_SUBGROUPS = new Set(CANONICAL_GROUPS.flatMap((g) => g.subgroups.map((s) => s.code)).filter((c) => !SYSTEM_SUBGROUPS.has(c)))

export type DemoCleanupReport = {
  propertyId: string
  propertyName: string
  deleted: string[]
  deactivated: string[]
  kept: { code: string; usedBy: string[] }[]
  subgroupsDeleted: string[]
  outletsUnlinked: string[]
}

type CodeRow = Awaited<ReturnType<typeof loadCodes>>[number]

function loadCodes(propertyId: string) {
  return prisma.chargeCode.findMany({
    where: { propertyId, isSystem: false },
    include: {
      chargeSubgroup: { include: { outlet: { select: { name: true, outletType: true } } } },
      outletCharges: { include: { outlet: { select: { name: true } } } },
      generatedBy: { include: { generatorCode: { select: { code: true, description: true, isSystem: true, chargeSubgroup: { include: { outlet: { select: { outletType: true } } } } } } } },
      _count: {
        select: {
          folioLineItems: true, payments: true, paymentMethods: true, allocations: true, ratePlans: true,
          routingRules: true, feeRules: true, excursionTypes: true, spaTreatments: true,
        },
      },
    },
  })
}

/** Still exactly what the seeder or the outlet provisioning created. */
function isDemo(c: { code: string; description: string; isSystem?: boolean; chargeSubgroup: { code: string; outlet: { outletType: string } | null } }): boolean {
  if (c.isSystem || SYSTEM_CODES.has(c.code)) return false
  if (DEMO_CODES.get(c.code) === c.description) return true
  const outlet = c.chargeSubgroup.outlet
  if (!outlet) return false
  const nn = c.chargeSubgroup.code.slice(0, 2)
  return (OUTLET_CODE_TEMPLATES[outlet.outletType] ?? []).some((t) => `${nn}${t.suffix}` === c.code && t.description === c.description)
}

async function usedBy(c: CodeRow): Promise<string[]> {
  const n = c._count
  const uses: string[] = []
  if (n.ratePlans) uses.push(`${n.ratePlans} rate plan(s)`)
  if (n.allocations) uses.push(`${n.allocations} allocation(s)`)
  if (n.paymentMethods) uses.push(`${n.paymentMethods} payment method(s)`)
  if (n.feeRules) uses.push(`${n.feeRules} fee rule(s)`)
  if (n.spaTreatments) uses.push(`${n.spaTreatments} spa treatment(s)`)
  if (n.excursionTypes) uses.push(`${n.excursionTypes} excursion type(s)`)
  if (n.routingRules) uses.push(`${n.routingRules} routing rule(s)`)
  const transport = await prisma.reservationTransport.count({ where: { chargeCodeId: c.id } })
  if (transport) uses.push(`${transport} transport leg(s)`)
  // Generated FROM one of the property's own codes (not another demo code, which goes too).
  const ownGenerators = c.generatedBy.filter((g) => !isDemo({ ...g.generatorCode, chargeSubgroup: { code: g.generatorCode.chargeSubgroup.code, outlet: g.generatorCode.chargeSubgroup.outlet } }))
  if (ownGenerators.length) uses.push(`generated by ${ownGenerators.map((g) => g.generatorCode.code).join(", ")}`)
  return uses
}

export async function cleanupDemoChargeCodes(propertyId: string, { apply }: { apply: boolean }): Promise<DemoCleanupReport> {
  const property = await prisma.property.findUniqueOrThrow({ where: { id: propertyId }, select: { name: true } })
  const report: DemoCleanupReport = { propertyId, propertyName: property.name, deleted: [], deactivated: [], kept: [], subgroupsDeleted: [], outletsUnlinked: [] }

  const codes = (await loadCodes(propertyId)).filter(isDemo)
  const toDelete: CodeRow[] = []
  const toDeactivate: CodeRow[] = []
  for (const c of codes) {
    if (c._count.folioLineItems > 0 || c._count.payments > 0) {
      if (c.isActive) toDeactivate.push(c)
      continue
    }
    const uses = await usedBy(c)
    if (uses.length) report.kept.push({ code: `${c.code} ${c.description}`, usedBy: uses })
    else toDelete.push(c)
  }
  report.deleted = toDelete.map((c) => `${c.code} ${c.description}`)
  report.deactivated = toDeactivate.map((c) => `${c.code} ${c.description}`)
  report.outletsUnlinked = [...new Set(toDelete.flatMap((c) => c.outletCharges.map((l) => l.outlet.name)))]

  // Subgroups left empty: the seeded demo defaults, and any an outlet was provisioned with.
  const deletedIds = new Set(toDelete.map((c) => c.id))
  const subgroups = await prisma.chargeSubgroup.findMany({
    where: { propertyId, OR: [{ code: { in: [...DEMO_SUBGROUPS] } }, { outletId: { not: null } }] },
    include: { chargeCodes: { select: { id: true } } },
  })
  const emptySubgroups = subgroups.filter((s) => !SYSTEM_SUBGROUPS.has(s.code) && s.chargeCodes.every((c) => deletedIds.has(c.id)))
  report.subgroupsDeleted = emptySubgroups.map((s) => `${s.code} ${s.name}`)

  if (apply) {
    await prisma.$transaction(async (tx) => {
      if (toDeactivate.length) await tx.chargeCode.updateMany({ where: { id: { in: toDeactivate.map((c) => c.id) } }, data: { isActive: false } })
      // Generates and outlet links cascade with the code.
      if (toDelete.length) await tx.chargeCode.deleteMany({ where: { id: { in: [...deletedIds] } } })
      if (emptySubgroups.length) await tx.chargeSubgroup.deleteMany({ where: { id: { in: emptySubgroups.map((s) => s.id) } } })
    })
  }
  return report
}
