import { NextResponse } from "next/server";

// Minting the inbound webhook URL is an OSTA-LEVEL action (app-owner decision,
// 2026-08-03): the URL is pasted into Beds24's webhook settings, and under the
// master-account topology the person with access to that Beds24 account is the app
// owner, not the tenant. A tenant minting one would rotate a credential they cannot
// then install — silently breaking inbound bookings until someone noticed.
//
// Refused here rather than only hidden in the Hub UI. The platform-side equivalent is
// POST /api/osta/channels/connections/[id]/webhook.
export async function POST() {
  return NextResponse.json(
    {
      error:
        "The inbound webhook URL is generated by Osta, who installs it in the channel manager. Contact Osta if it needs to be reissued.",
    },
    { status: 403 }
  );
}
